from typing import List

from langchain_core.documents import Document
from pydantic import BaseModel, Field, field_validator
from fastapi import UploadFile


class DocumentModel(BaseModel):
    page_content: str = Field(..., description="The content of the page.")
    metadata: dict = Field(..., description="The metadata of the page.")


class PlannerInput(BaseModel):
    file: UploadFile = Field(..., description="The file to be processed by the planner.")


class PlannerOutput(BaseModel):
    plan: List[str] = Field(..., description="The plan generated by the planner.")
    chunks: List[DocumentModel] = Field(..., description="The chunks of the document.")
